[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet restore", "dotnet publish ShopFortnite/ShopFortnite.csproj -c Release -o out"]

[phases.start]
cmd = "cd out && dotnet ShopFortnite.dll"
